
server:
  port: 9106
eureka:
  instance:
    status-page-url-path: /info
    health-check-url-path: /health
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
      
spring:
   datasource:
      url: jdbc:mysql://120.26.38.208:3306/spring-china?useSSL=true
      username: spring-china
      password: 1qaz@WSX
      driver-class-name: com.mysql.jdbc.Driver
mybatis:
   mapperLocations: classpath:org/spring/china/admin/mapping/*.xml
   typeAliasesPackage: org.spring.china.base.pojo
   
hystrix:
   command:
      default:
         execution:
            isolation:
              thread:
                 timeoutInMilliseconds: 15000


            

